### PR TITLE
implementing bdd-stdin

### PR DESCRIPTION
**Pull request by pointnet**
What about this for testing ?
Still have trouble with default loader, I'm probably missing something.

### CODE REVIEW

**Comment by pointnet** [comment]
Time to sleep after seeing that successful check!

**Comment by doowb** [comment]
I had seen the `bdd-stdin` lib before but forgot it's name. I like this and passing the regexp into the `exists` function.

**Comment by jonschlinkert** [comment]
> I like this and passing the regexp into the exists function.

yeah we do this somewhere else, maybe we should create a test util for this, since we're doing this everywhere

**Comment by jonschlinkert** [comment]
> Still have trouble with default loader, I'm probably missing something.

see [this commit](https://github.com/generate/generate-license/commit/9a149e56d4c36c797c5b2d34278ad2619d673615#diff-1917a60f372344e0d19f78dd69a543d3R318), hopefully that helps explain

**Comment by jonschlinkert** [comment]
@pointnet this is awesome, great work!

**Comment by pointnet** [comment]
> see this commit, hopefully that helps explain
That makes more sense for me now!

We still need to change the documentation, there's two little mistakes:

```
What will happen?

Running $ gen license will run the generator's default task, which creates a new MIT LICENSE file in the current working directory. The template can be customized.
```
This is not right anymore, this is running the `choose-license` by default.

```
Overriding templates

You can override a template by adding a template of the same name to the templates directory in user home.

For example, to override the LICENSE template, add a template at the following path ~/generate/generate-license/templates/LICENSE, where ~/ is the user-home directory that os.homedir() resolves on your system.
```
I thought the templates needs to have the same names as those in the `./templates` folder, am I wrong ?

**Comment by jonschlinkert** [comment]
> We still need to change the documentation, there's two little mistakes:

Indeed! I found the first mistake and fixed it locally. I can do the other now. 

> I thought the templates needs to have the same names as those in the ./templates folder, am I wrong ?

you are correct, `LICENSE` was supposed to be an arbitrary name. I also caught this locally and changed it to `foo.tmp` so we can generalize this documentation. 

I'd really love to come up with a good template/outline we can use to generate the readme for all generators. Any feedback is welcome. I tried something different on [generate-verbfile](https://github.com/generate/generate-verbfile). The docs are split between the readme and `docs.md`. My thinking is that we should probably try to focus on "getting started" on the readme, but provide more information for nerds like me who like to read that stuff lol.

**Comment by pointnet** [comment]
hotfix to intercept `generate` console messages. #5

**Pull request merged**
