### PR TITLE
Feature/rework

### PR DESCRIPTION
**Pull request by pointnet**
Adding all licenses of github website.

A task per license, defaults to choose, using question-cache.

Don't know how to do for tests, any ideas ?

### CODE REVIEW

**Comment by jonschlinkert** [comment]
Wow this is awesome! Thanks! 

> Don't know how to do for tests, any ideas ?

testing prompts can be difficult. Let's get this merged then we can brainstorm on how to do unit tests. Worst case we can implement unit tests for file generation only, and circumvent the prompts

**Comment by pointnet** [comment]
I didn't bumped the version, I let you see for that.

**Comment by pointnet** [comment]
And there's also an issue with template generation.

Try `gen license:agpl-3.0`, look at the first line of the generated license, spaces are lost, it's not as in https://github.com/generate/generate-license/blob/master/templates/agpl-3.0.tmpl

**Comment by jonschlinkert** [comment]
I think I know why, I'll take a look, thanks

**Comment by jonschlinkert** [comment]
yeah, it's because whitespace is removed after the yaml front matter is stripped. What it should be doing instead, is only removing leading lines when they are 100% whitespace. I can fix that now

**Comment by jonschlinkert** [comment]
> I didn't bumped the version, I let you see for that.

that's good, generally I like to do this after reviewing. thanks! 

working on that whitespace issue now

**Comment by jonschlinkert** [comment]
Regarding unit tests, for now I suggest we either make the default test do something other than prompt, like generate mit license by default, or we can just update the tests to run the tasks that won't prompt. do you have a preference?

**Comment by pointnet** [comment]
what about that #2 ?

**Pull request merged**
